version: '3.9'

services:
  diploma-postgres:
    image: postgres:latest
    container_name: diploma-postgres
    restart: unless-stopped
    volumes:
      - /home/deployment/diploma/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5438:5432'

  diploma-app:
    image: justhoshion/diploma
    container_name: diploma-app
    restart: unless-stopped
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=diploma-postgres
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=src.app.settings
    ports:
      - '8888:8000'