# Generated by Django 5.2 on 2025-05-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_translator_newstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstranslation',
            name='translator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.translator'),
            preserve_default=False,
        ),
    ]
