# Generated by Django 5.2 on 2025-05-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newstranslation_translator'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.largelanguagemodel')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newstranslation')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.largelanguagemodel')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newstranslation')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.prompt')),
            ],
        ),
    ]
